### PR TITLE
Fixed the quota issue for evaluateVariable()

### PR DESCRIPTION
**Pull request by sevrugin**
Fixed the error "src/Template.php(212) : eval()'d code:1" if some string variable has the single quote

### CODE REVIEW

**Comment by sevrugin** [comment]
@byjg can you please merge my PR and make a new release?
Thanks!

**Comment by byjg** [comment]
Thank you for the PR. I merged already. I'll conduce some tests during the day and if everything is OK, I'll create a release number. 

For now, you can use `dev-master`.

**Comment by sevrugin** [comment]
Thank you so much! I will wait for the release

**Comment by byjg** [comment]
Release `4.9.1` published.

**Pull request merged**
